#pragma warning disable 1591
namespace TikzDemo.ILNumerics_deploy {
    /// <summary>
    /// This type supports ILNumerics infrastructure. Do not edit the code!
    /// </summary>
    /// <remarks>This type is automatically generated by ILNumerics Ultimate VS. If you encounter problems compiling this file, make sure to reference ILNumerics.Core in your project!</remarks>
    [System.ComponentModel.LicenseProvider(typeof(ILNumerics.Licensing.ILLicenseProvider))]  // <- ILNumerics.Core is needed here!
    public partial class ILLicHelper_3942b862afb04bc8a46ac9ae464a9edb_ {
        /// <summary>
        /// Licensing Helper (internal use)
        /// </summary>
        public ILLicHelper_3942b862afb04bc8a46ac9ae464a9edb_() { System.ComponentModel.LicenseManager.Validate(typeof(ILLicHelper_3942b862afb04bc8a46ac9ae464a9edb_), this); } }
}