#pragma warning disable 1591
namespace ILNumerics_Licensing {
    /// <summary>
    /// This type supports ILNumerics infrastructure. Do not edit the code!
    /// </summary>
    /// <remarks>This type is automatically generated by ILNumerics Ultimate VS. If you encounter problems compiling this file, make sure to reference ILNumerics.Core in your project!</remarks>
    [System.ComponentModel.LicenseProvider(typeof(ILNumerics.Licensing.ILLicenseProvider))]  // <- ILNumerics.Core is needed here!
    public partial class ILLicHelper_69340a566b5d48cb864bca0effb54917_ { public ILLicHelper_69340a566b5d48cb864bca0effb54917_() { System.ComponentModel.LicenseManager.Validate(typeof(ILLicHelper_69340a566b5d48cb864bca0effb54917_), this); } }
}